version: 0.0
os: linux
files:
  - source: /index.html
    destination: /opt/bitnami/apache/htdocs/
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/start_server
      timeout: 600
      runas: root

  ApplicationStop:
    - location: scripts/stop_server
      timeout: 600
      runas: root
