version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/start_server
      timeout: 300
      runas: bitnami
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: bitnami
      commands:
        - cp /var/www/html/index.html /opt/bitnami/apache/htdocs/index.html
