version: 0.0
os: linux
files:
  - source: /index.html
    destination: /opt/bitnami/apache/htdocs/
    runas: bitnami
hooks:
  BeforeInstall:
    - location: scripts/start_server
      timeout: 600
      runas: bitnami
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 600
      runas: bitnami
