version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/start_server
      timeout: 300
      runas: root
      commands:
        - cp -f /index.html /var/www/html/index.html
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
